<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InstructorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('instructors')->insert([
            [
                "name" => "James Taylor",
                "description" => "I'm a maths teacher in Colombo",
                "heading" => "AL Maths Teacher",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Maths",
                "curriculum" => "OL",
                "grade" => 10,
                "class_type" => "In Person",
                "hourly_rate" => 10.00,
                "rating" => 4.00,
                "location" => "Colombo",
                "region" => "Western",
                "classes_offered" => "1-1, group classes",
                "class_duration" => 30,
                "ages_teach" => "1-5"
            ],
            [
                "name" => "Sarah Johnson",
                "description" => "Specialized in teaching Science in Kandy",
                "heading" => "Science Teacher",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Science",
                "curriculum" => "OL",
                "grade" => 9,
                "class_type" => "Online",
                "hourly_rate" => 12.00,
                "rating" => 5.00,
                "location" => "Kandy",
                "region" => "Central",
                "classes_offered" => "1-1",
                "class_duration" => 60,
                "ages_teach" => "6-10"
            ],
            [
                "name" => "Amila Perera",
                "description" => "Art teacher in Galle with 5 years of experience",
                "heading" => "Art for Beginners",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Art",
                "curriculum" => "OL",
                "grade" => 8,
                "class_type" => "In Person",
                "hourly_rate" => 8.00,
                "rating" => 3.50,
                "location" => "Galle",
                "region" => "Southern",
                "classes_offered" => "1-1",
                "class_duration" => 45,
                "ages_teach" => "6-10"
            ],
            [
                "name" => "Chandana Silva",
                "description" => "Mathematics tutor for advanced students",
                "heading" => "Mathematics Advanced Level",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Maths",
                "curriculum" => "AL",
                "grade" => 12,
                "class_type" => "In Person and Online",
                "hourly_rate" => 15.00,
                "rating" => 4.80,
                "location" => "Negombo",
                "region" => "Western",
                "classes_offered" => "group classes",
                "class_duration" => 90,
                "ages_teach" => "11-15"
            ],
            [
                "name" => "Deepika Wijesinghe",
                "description" => "Science teacher passionate about experiments",
                "heading" => "OL Science Teacher",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Science",
                "curriculum" => "OL",
                "grade" => 9,
                "class_type" => "Online",
                "hourly_rate" => 13.00,
                "rating" => 4.50,
                "location" => "Kurunegala",
                "region" => "North Western",
                "classes_offered" => "1-1, group classes",
                "class_duration" => 60,
                "ages_teach" => "11-15"
            ],
            [
                "name" => "Samantha Gunawardena",
                "description" => "I teach art classes with a creative approach",
                "heading" => "Creative Art Classes",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Art",
                "curriculum" => "AL",
                "grade" => 11,
                "class_type" => "In Person",
                "hourly_rate" => 9.00,
                "rating" => 4.20,
                "location" => "Colombo",
                "region" => "Western",
                "classes_offered" => "group classes",
                "class_duration" => 45,
                "ages_teach" => "11-15"
            ],
            [
                "name" => "Tharanga Bandara",
                "description" => "Teaching Maths to primary students in Batticaloa",
                "heading" => "Primary Maths Teacher",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Maths",
                "curriculum" => "OL",
                "grade" => 5,
                "class_type" => "In Person",
                "hourly_rate" => 7.00,
                "rating" => 3.90,
                "location" => "Batticaloa",
                "region" => "Eastern",
                "classes_offered" => "1-1",
                "class_duration" => 30,
                "ages_teach" => "1-5"
            ],
            [
                "name" => "Nihal Karunarathne",
                "description" => "Specialist in teaching high school level science",
                "heading" => "Science Teacher",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Science",
                "curriculum" => "OL",
                "grade" => 10,
                "class_type" => "Online",
                "hourly_rate" => 11.00,
                "rating" => 4.30,
                "location" => "Gampaha",
                "region" => "Western",
                "classes_offered" => "1-1",
                "class_duration" => 60,
                "ages_teach" => "6-10"
            ],
            [
                "name" => "Ruwan Abeysinghe",
                "description" => "Experienced art teacher for middle school students",
                "heading" => "Art Teacher",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Art",
                "curriculum" => "OL",
                "grade" => 7,
                "class_type" => "In Person",
                "hourly_rate" => 6.00,
                "rating" => 4.10,
                "location" => "Kalutara",
                "region" => "Western",
                "classes_offered" => "group classes",
                "class_duration" => 40,
                "ages_teach" => "6-10"
            ],
            [
                "name" => "Priyanka Rathnayake",
                "description" => "Teaching advanced mathematics",
                "heading" => "Advanced Mathematics",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Maths",
                "curriculum" => "AL",
                "grade" => 13,
                "class_type" => "In Person",
                "hourly_rate" => 20.00,
                "rating" => 4.90,
                "location" => "Matara",
                "region" => "Southern",
                "classes_offered" => "group classes",
                "class_duration" => 90,
                "ages_teach" => "11-15"
            ],
            [
                "name" => "Dinesh Perera",
                "description" => "Science teacher for beginners",
                "heading" => "Science for Beginners",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Science",
                "curriculum" => "OL",
                "grade" => 6,
                "class_type" => "In Person and Online",
                "hourly_rate" => 14.00,
                "rating" => 4.60,
                "location" => "Badulla",
                "region" => "Uva",
                "classes_offered" => "1-1",
                "class_duration" => 60,
                "ages_teach" => "6-10"
            ],
            [
                "name" => "Namal Ekanayake",
                "description" => "Teaching art with a modern perspective",
                "heading" => "Modern Art Classes",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Art",
                "curriculum" => "AL",
                "grade" => 11,
                "class_type" => "In Person",
                "hourly_rate" => 10.00,
                "rating" => 3.70,
                "location" => "Ratnapura",
                "region" => "Sabaragamuwa",
                "classes_offered" => "group classes",
                "class_duration" => 45,
                "ages_teach" => "11-15"
            ],
            [
                "name" => "Niluka Rajapakse",
                "description" => "Helping students achieve excellence in maths",
                "heading" => "Mathematics Expert",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Maths",
                "curriculum" => "OL",
                "grade" => 9,
                "class_type" => "Online",
                "hourly_rate" => 10.00,
                "rating" => 4.50,
                "location" => "Nuwara Eliya",
                "region" => "Central",
                "classes_offered" => "1-1",
                "class_duration" => 60,
                "ages_teach" => "11-15"
            ],
            [
                "name" => "Lakshmi Fonseka",
                "description" => "Innovative approaches to teaching science",
                "heading" => "Science Tutor",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Science",
                "curriculum" => "AL",
                "grade" => 12,
                "class_type" => "In Person",
                "hourly_rate" => 17.00,
                "rating" => 4.70,
                "location" => "Anuradhapura",
                "region" => "North Central",
                "classes_offered" => "group classes",
                "class_duration" => 60,
                "ages_teach" => "11-15"
            ],
            [
                "name" => "Kavinda Senarath",
                "description" => "Teaching mathematics with practical examples",
                "heading" => "Practical Maths Teacher",
                "cover_pic" => "https://via.placeholder.com/150",
                "profile_pic" => "https://via.placeholder.com/150",
                "subject" => "Maths",
                "curriculum" => "AL",
                "grade" => 11,
                "class_type" => "In Person and Online",
                "hourly_rate" => 15.00,
                "rating" => 4.40,
                "location" => "Jaffna",
                "region" => "Northern",
                "classes_offered" => "1-1",
                "class_duration" => 75,
                "ages_teach" => "6-10"
            ],
        ]);
    }
}
